### ISSUE TITLE
preparing small dataset

### ISSUE THREAD

**Issue by djarecka** [ReproNim/OHBMEducation-2022#2]
Since we ask people to clone the data repository from ReproNim repo, perhaps we could prepare 4 or 5 different branches that will have the subset of datasets, with edited `participants.tsv`

I'm afraid that this part might take a lot of time, it's "simple", but many mistakes possible (e.g. deleting the same dataset as in Dave's example), and if people don't have experience with bash/git reverting the mistakes will take time. 
At the same time, this part doesn't really have "educational" goal.

**Comment by dnkennedy** [comment]
Yeh, I thought about that. I think the creating dataset issues for newbies will not so much be git, or even removing datasets, as the JupyterHub has a graphical file manager we can use (I think, will double check). But rather the editing of the participants.tsv. I did it in vi, which of course we don't want to teach, but there is another simple text editor we use, if I remember.

Anyway, if we feel this is too much, we can resort to the prepackaged mini-datasets at @djarecka is suggesting...

**Comment by djarecka** [comment]
oh, ok, perhaps with Jupuyter Hub it might be easier/faster. 

I meant git in case someone removes too much by mistake.

**Comment by dnkennedy** [comment]
I'm going to close this, will reopen if we decide that the jupyterhub editing is too hard...
