### ISSUE TITLE
comments to the exercise text

### ISSUE THREAD

**Issue by djarecka** [ReproNim/OHBMEducation-2022#5]
@dnkennedy 

I've created separate issues for bigger things, but here just want to collect smaller comments I had:
- `sub-4601` and `sub-4227` don't exist, perhaps you meant `sub-RC4106` and `sub-RC4227`
- when I run BIDS validation I got warnings, is this what you expected?
    ````
	1: [WARN] Tabular file contains custom columns not described in a data dictionary (code: 82 - CUSTOM_COLUMN_WITHOUT_DESCRIPTION)
		./participants.tsv
			Evidence: Columns: age, sex, diagnosis not defined, please define in: /participants.json

	Please visit https://neurostars.org/search?q=CUSTOM_COLUMN_WITHOUT_DESCRIPTION for existing conversations about this issue.

        Summary:               Available Tasks:        Available Modalities: 
        12 Files, 3.8KB                                MRI                   
        2 - Subjects                                                         
        2 - Sessions                                                         
     ```

- I'm guessing that you wanted to create `my_analysis` outside `my_data`, is that right? Perhaps it should be clarified. Also, could we clone `my_ds001907-EDU` from `my_data` instead of from GitHub when creating `rawdata`?

**Comment by dnkennedy** [comment]
Thanks, @djarecka .  I will fix those subject names.

the BIDS warning is the one I expected

yes, I was intending ```my_analysis``` to be outside of ```my_data```. will try to clarify.

cloning ```my_data``` instead, I was also wondering about that, but followed @yarikoptic 's guidance. What would the syntax be?
